spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  docker:
    compose:
      enable: false
      file: docker-compose.yml
  kafka:
    bootstrap-servers: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
server:
  port: 8086
